#!/bin/bash -ex                                                                                                    
rm -fr data && docker-compose stop; docker-compose rm -f ; docker-compose build; docker-compose up --force-recreate 
